name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update to stable
        run: |
          rustup self update
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
